name: tokenbridge-contracts

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install
        if: ${{ !steps.npm-cache.outputs.cache-hit }}
      - run: yarn lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: node_modules
          key: v2-${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install
        if: ${{ !steps.npm-cache.outputs.cache-hit }}
      - run: yarn test:gasreport
  analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: node_modules
          key: v2-${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install
        if: ${{ !steps.npm-cache.outputs.cache-hit }}
      - run: yarn run compile
      - uses: crytic/slither-action@v0.1.1
        continue-on-error: true
        id: slither
        with:
          ignore-compile: true
          sarif: results.sarif
      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.slither.outputs.sarif }}
  deploy-smoketest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: node_modules
          key: v2-${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install
        if: ${{ !steps.npm-cache.outputs.cache-hit }}
      - name: Run hardhat node in background
        run: ./node_modules/.bin/hardhat node &

      - run: yarn deploy:smoketest
  contract-size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: node_modules
          key: v2-${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install
        if: ${{ !steps.npm-cache.outputs.cache-hit }}
      - run: yarn contract-size
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: node_modules
          key: v2-${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install
        if: ${{ !steps.npm-cache.outputs.cache-hit }}
      - run: yarn coverage
