name: tokenbridge-contracts

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install
        if: ${{ !steps.npm-cache.outputs.cache-hit }}
      - run: yarn lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: node_modules
          key: v2-${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install
        if: ${{ !steps.npm-cache.outputs.cache-hit }}
      - run: yarn test
  contract-size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: node_modules
          key: v2-${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install
        if: ${{ !steps.npm-cache.outputs.cache-hit }}
      - run: yarn contract-size
  gasreport:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: node_modules
          key: v2-${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install
        if: ${{ !steps.npm-cache.outputs.cache-hit }}
      - run: yarn test:gasreport:ci
        env:
          CC_SECRET: ${{ secrets.CC_SECRET }}
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: node_modules
          key: v2-${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install
        if: ${{ !steps.npm-cache.outputs.cache-hit }}
      - run: yarn coverage
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
