name: tokenbridge-contracts

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install
        if: ${{ !steps.npm-cache.outputs.cache-hit }}
      - run: yarn lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: node_modules
          key: v2-${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install
        if: ${{ !steps.npm-cache.outputs.cache-hit }}
      - run: yarn test:gasreport
  deploy-smoketest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: node_modules
          key: v2-${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install
        if: ${{ !steps.npm-cache.outputs.cache-hit }}
      - name: Run hardhat node in background
        run: ./node_modules/.bin/hardhat node &

      - run: yarn deploy:smoketest
  contract-size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: node_modules
          key: v2-${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install
        if: ${{ !steps.npm-cache.outputs.cache-hit }}
      - run: yarn contract-size
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: node_modules
          key: v2-${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install
        if: ${{ !steps.npm-cache.outputs.cache-hit }}
      - run: yarn coverage
